# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Younas.io"
description: > # this means to ignore newlines until "email:"
   A new tech blog

email: jonas.liley@owasp.org
#blog logo
logo: "/assets/images/hacker.png"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/stockholm.jpg"

name: 'Jonas Liley'
author: 'Jonas Liley'
author_image: "/assets/images/hacker.png"

paginate:	5

url: "http://jonas-liley.***.***" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
#twitter_handle: ''

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	github
    url:	https://github.com/Jonas-Liley
    desc:	Follow me on GitHub
    share_url:
    share_title:
    share_link:

  - icon:	linkedin
    url:	https://www.linkedin.com/in/jonas-liley/
    desc:	Check me out on LinkedIn
    share_url:
    share_title:
    share_link:
